title: Julian Ritz-Barr
url: "https://julianritzbarr.com"
baseurl:
remote_theme: ankitsultana/researcher@gem
markdown: kramdown
github: f630bef01f74c78c96a8b1e7faa373f5dc408ecb
tracking_id: #
repository: "juicelightning"
footer: yes
footer_url: "https://github.com/juized"
footer_text: "JRB Forked from Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

plugins:
  - jemoji

  
nav:
 - name: "<b>Resume</b>"
   link: "https://juized.github.io/juicelightning/Rusume(pdf).pdf"
 - name: "<b> DlaxV Stats-Ligapolka </b>"
   link: "http://stats.pointbench.com/illph/2019/index.php?cmd=player-points"
 - name: "<b>Contact</b>"
   link: "https://juized.github.io/juicelightning/contact/
