title: Julian Ritz-Barr
url: "https://julianritzbarr.tk"
baseurl:
remote_theme: ankitsultana/researcher@gem
markdown: kramdown
github: f630bef01f74c78c96a8b1e7faa373f5dc408ecb
tracking_id: #
repository: "Juicelightning"
footer: yes
footer_url: "https://github.com/juized"
footer_text: "JRB Forked from Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

plugins:
  - jemoji

  
nav:
 - name: "DlaxV Stats"
   link: "http://stats.pointbench.com/illph/2019/index.php?cmd=player-points"
 - name: "Contact"
   link: "https://twitter.com/Btc_anyone"
