title: Julian Ritz-Barr
url: "https://juicylightning.com"
baseurl:
remote_theme: ankitsultana/researcher@gem
markdown: kramdown
github: f630bef01f74c78c96a8b1e7faa373f5dc408ecb
tracking_id: #

footer: yes
footer_url: "https://github.com/juized"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

plugins:
  - jemoji

  
nav:
 - name: "About"
   link: "/researcher/"
 - name: "Contact"
   link: "https://twitter.com/justinmoen"
