title: Justin Moon
url: "https://justinmoon.com"
baseurl: ""
remote_theme: ankitsultana/researcher@gem
markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/juized"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

plugins:
  - jemoji

  
nav:
 - name: "About"
   link: "/researcher/"
 - name: "Contact"
   link: "https://twitter.com/justinmoen"
